version: '3.8'

services:
  db:
    image: mysql:8
    container_name: companydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: companydb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  node-api:
    build: .
    command: ["./wait-for-db.sh"]
    container_name: node-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_DATABASE: companydb
      DB_PORT: 3306
      PORT: 3000
